import { defineConfig } from 'vitest/config';
import { resolve } from 'path';
import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'unit',
          environment: 'jsdom',
          setupFiles: ['src/test/setup.ts'],
          include: ['src/**/*.test.{ts,tsx}'],
          globals: true,
          coverage: {
            provider: 'v8',
            reporter: ['text', 'html', 'lcov'],
            reportsDirectory: './coverage',
            all: false,
            thresholds: {
              lines: 70,
              functions: 70,
              branches: 70,
              statements: 70,
            },
            include: [
              'src/components/atoms/**',
              'src/components/molecules/**',
              'src/components/organisms/**',
              'src/components/templates/**',
              'src/services/**',
              'src/store/**',
              'src/utils/**',
            ],
            exclude: [
              '**/*.stories.*',
              '**/*.test.*',
              '**/*.spec.*',
              '**/node_modules/**',
              '**/__tests__/**',
              'src/**/*.d.ts',
              'src/test/**',
              'src/locales/**',
              'src/styles/**',
              'src/layouts/**',
              'src/hooks/**',
              'src/pages/**',
              'src/components/pages/**',
              'src/components/atoms/AuthGuard/**',
              'src/components/atoms/Toast/**',
              'src/components/molecules/AdminMatchResultForm/**',
              'src/components/molecules/LoginForm/**',
              'src/components/molecules/RegisterForm/**',
              'src/components/molecules/PredictorSelector/**',
              'src/components/organisms/AdminMatchList/**',
              'src/components/organisms/AdminMatchesPage/**',
              'src/components/organisms/BestPlayersForm/**',
              'src/components/organisms/FinalPhaseForm/**',
              'src/components/organisms/GroupPredictionForm/**',
              'src/components/organisms/KnockoutBracketForm/**',
              'src/components/organisms/PWAInstall/**',
              'src/components/organisms/ToastProvider/**',
            ],
          },
        },
        resolve: {
          alias: {
            '@': resolve(__dirname, './src'),
            '@atoms': resolve(__dirname, './src/components/atoms'),
            '@molecules': resolve(__dirname, './src/components/molecules'),
            '@organisms': resolve(__dirname, './src/components/organisms'),
            '@templates': resolve(__dirname, './src/components/templates'),
            '@layouts': resolve(__dirname, './src/layouts'),
            '@styles': resolve(__dirname, './src/styles'),
            '@utils': resolve(__dirname, './src/utils'),
            '@hooks': resolve(__dirname, './src/hooks'),
            '@store': resolve(__dirname, './src/store'),
            '@services': resolve(__dirname, './src/services'),
            '@app-types': resolve(__dirname, './src/types'),
            '@locales': resolve(__dirname, './src/locales'),
          },
        },
      },
      {
        test: {
          name: 'storybook',
          environment: 'happy-dom',
          setupFiles: ['.storybook/vitest.setup.ts'],
        },
        plugins: [
          storybookTest({ configDir: resolve(__dirname, '.storybook') }),
        ],
        resolve: {
          alias: {
            '@': resolve(__dirname, './src'),
            '@atoms': resolve(__dirname, './src/components/atoms'),
            '@molecules': resolve(__dirname, './src/components/molecules'),
            '@organisms': resolve(__dirname, './src/components/organisms'),
            '@templates': resolve(__dirname, './src/components/templates'),
            '@layouts': resolve(__dirname, './src/layouts'),
            '@styles': resolve(__dirname, './src/styles'),
            '@utils': resolve(__dirname, './src/utils'),
            '@hooks': resolve(__dirname, './src/hooks'),
            '@store': resolve(__dirname, './src/store'),
            '@services': resolve(__dirname, './src/services'),
            '@app-types': resolve(__dirname, './src/types'),
            '@locales': resolve(__dirname, './src/locales'),
          },
        },
      },
    ],
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@atoms': resolve(__dirname, './src/components/atoms'),
      '@molecules': resolve(__dirname, './src/components/molecules'),
      '@organisms': resolve(__dirname, './src/components/organisms'),
      '@templates': resolve(__dirname, './src/components/templates'),
      '@layouts': resolve(__dirname, './src/layouts'),
      '@styles': resolve(__dirname, './src/styles'),
      '@utils': resolve(__dirname, './src/utils'),
      '@hooks': resolve(__dirname, './src/hooks'),
      '@store': resolve(__dirname, './src/store'),
      '@services': resolve(__dirname, './src/services'),
      '@app-types': resolve(__dirname, './src/types'),
      '@locales': resolve(__dirname, './src/locales'),
    },
  },
});
